version: '3'

services:

  # Proxies requests to internal services
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse-proxy
    depends_on:
        - server-one
        - server-two
        - server-home
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  server-home:
    image: server-home
    container_name: server-home
    build:
      context: ./server-home
    ports:
      - 5000:5000
    restart: on-failure

  server-one:
    image: server-one
    container_name: server-one
    build:
      context: ./server-one
    ports:
      - 5001:5000
    restart: on-failure

  server-two:
    image: server-two
    container_name: server-two
    build:
      context: ./server-two
    ports:
      - 5002:5000
    restart: on-failure